// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RcppCAF_h__
#define __RcppCAF_h__

#include "RcppCAF_RcppExports.h"

#endif // __RcppCAF_h__
