// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppCAF.h"
#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// rcpp_caf_dist
Rcpp::NumericVector rcpp_caf_dist(SEXP inMatrix, SEXP ncore);
RcppExport SEXP RcppCAF_rcpp_caf_dist(SEXP inMatrixSEXP, SEXP ncoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type inMatrix(inMatrixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncore(ncoreSEXP);
    __result = Rcpp::wrap(rcpp_caf_dist(inMatrix, ncore));
    return __result;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int RcppCAF_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP RcppCAF_RcppExport_registerCCallable() { 
    R_RegisterCCallable("RcppCAF", "RcppCAF_RcppExport_validate", (DL_FUNC)RcppCAF_RcppExport_validate);
    return R_NilValue;
}
