// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_caf_dist
Rcpp::NumericMatrix rcpp_caf_dist(SEXP inMatrix, SEXP ncore);
RcppExport SEXP RcppCAF_rcpp_caf_dist(SEXP inMatrixSEXP, SEXP ncoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type inMatrix(inMatrixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncore(ncoreSEXP);
    __result = Rcpp::wrap(rcpp_caf_dist(inMatrix, ncore));
    return __result;
END_RCPP
}
