# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_caf_dist <- function(inMatrix, ncore) {
    .Call('RcppCAF_rcpp_caf_dist', PACKAGE = 'RcppCAF', inMatrix, ncore)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RcppCAF_RcppExport_registerCCallable', PACKAGE = 'RcppCAF')
})
